// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = (import.meta.env as { VITE_SUPABASE_URL?: string }).VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = (import.meta.env as { VITE_SUPABASE_ANON_KEY?: string }).VITE_SUPABASE_ANON_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error('Missing required Supabase environment variables: VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY');
}

if ((import.meta.env as { DEV?: boolean })?.DEV) {
  const isLocal = SUPABASE_URL?.includes('127.0.0.1') || false;
  console.log('🔗 CONNECTING TO:', isLocal ? 'LOCAL' : 'REMOTE', 'database at', SUPABASE_URL || 'undefined');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Re-export the URL for edge function calls that require subpaths
export const SUPABASE_URL_FOR_FUNCTIONS = SUPABASE_URL;