// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Prefer environment variables with safe fallbacks to current values
const SUPABASE_URL =
  (import.meta.env as { VITE_SUPABASE_URL?: string })?.VITE_SUPABASE_URL ?? 
  (import.meta.env as { SUPABASE_URL?: string })?.SUPABASE_URL ?? 
  "https://hhqnvjxnsbwhmrldohbz.supabase.co";

const SUPABASE_PUBLISHABLE_KEY =
  (import.meta.env as { VITE_SUPABASE_ANON_KEY?: string })?.VITE_SUPABASE_ANON_KEY ?? 
  (import.meta.env as { SUPABASE_ANON_KEY?: string })?.SUPABASE_ANON_KEY ??
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhocW52anhuc2J3aG1ybGRvaGJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NDY1NjYsImV4cCI6MjA2ODMyMjU2Nn0.2OZ9I3wabTicL0CTGnAdQGj2A0fuh3CTRZvoCmiQS08";

// Local development configuration (commented out)
// const SUPABASE_URL = "http://127.0.0.1:54321";
// const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0";

// Debug: Show which database we're connecting to (dev only)
if ((import.meta.env as { DEV?: boolean })?.DEV) {
  const isLocal = SUPABASE_URL?.includes('127.0.0.1') || false;
  console.log('🔗 CONNECTING TO:', isLocal ? 'LOCAL' : 'REMOTE', 'database at', SUPABASE_URL || 'undefined');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Re-export the URL for edge function calls that require subpaths
export const SUPABASE_URL_FOR_FUNCTIONS = SUPABASE_URL;